USE Project_DB
GO

IF OBJECT_ID('tempdb..#companies') IS NOT NULL
DROP TABLE #companies

CREATE TABLE #companies (company_name VARCHAR(MAX))

INSERT INTO #companies VALUES('Farmers Insurance Group')
INSERT INTO #companies VALUES('Luxoft USA Inc')
INSERT INTO #companies VALUES('Cincinnati Bell Technology Solutions')
INSERT INTO #companies VALUES('BlackRock')
INSERT INTO #companies VALUES('CyberCoders')
INSERT INTO #companies VALUES('JP Morgan Chase')
INSERT INTO #companies VALUES('Spotify')
INSERT INTO #companies VALUES('Xoriant Corporation')
INSERT INTO #companies VALUES('Adroit Resources')
INSERT INTO #companies VALUES('Northrop Grumman')
INSERT INTO #companies VALUES('Envoy Consulting Group, Inc')
INSERT INTO #companies VALUES('Noblis')
INSERT INTO #companies VALUES('ARUP Laboratories')
INSERT INTO #companies VALUES('Perspecta')
INSERT INTO #companies VALUES('Pyramid Consulting, Inc.')
INSERT INTO #companies VALUES('Orpine.com')
INSERT INTO #companies VALUES('Apeiro Technologies')
INSERT INTO #companies VALUES('Bank of America')
INSERT INTO #companies VALUES('Sallie Mae')
INSERT INTO #companies VALUES('Taboola')
INSERT INTO #companies VALUES('VideoAmp')
INSERT INTO #companies VALUES('Apple')
INSERT INTO #companies VALUES('Amtex Enterprises')
INSERT INTO #companies VALUES('Sysmind, LLC')
INSERT INTO #companies VALUES('FocuzMindz')
INSERT INTO #companies VALUES('Digital Intelligence Systems, LLC')
INSERT INTO #companies VALUES('Advent Global Solutions, Inc.')
INSERT INTO #companies VALUES('Resource Informatics Group')
INSERT INTO #companies VALUES('Viri Technology')
INSERT INTO #companies VALUES('Kforce Technology Staffing')
INSERT INTO #companies VALUES('L3 Technologies')
INSERT INTO #companies VALUES('Apex Systems')
INSERT INTO #companies VALUES('Jefferson Frank')
INSERT INTO #companies VALUES('5 Star Global Recruitment Partners, LLC')
INSERT INTO #companies VALUES('IQVIA')
INSERT INTO #companies VALUES('Grant Thornton LLP')
INSERT INTO #companies VALUES('Experis')
INSERT INTO #companies VALUES('Staffing Technologies')
INSERT INTO #companies VALUES('Aerotek')
INSERT INTO #companies VALUES('Kraft Heinz Company')
INSERT INTO #companies VALUES('Criteo')
INSERT INTO #companies VALUES('Comcast')
INSERT INTO #companies VALUES('FireEye, Inc.')
INSERT INTO #companies VALUES('Eventbrite')
INSERT INTO #companies VALUES('Kforce Technology')
INSERT INTO #companies VALUES('Hamilton Technical Personnel')
INSERT INTO #companies VALUES('USM Business Systems')
INSERT INTO #companies VALUES('Ubergig')
INSERT INTO #companies VALUES('Infobahn Softworld Inc.')
INSERT INTO #companies VALUES('Payette Group')
INSERT INTO #companies VALUES('Spectra Group')
INSERT INTO #companies VALUES('IT Associates, Inc.')
INSERT INTO #companies VALUES('Veear')
INSERT INTO #companies VALUES('Cynet Systems')
INSERT INTO #companies VALUES('3K Technologies')
INSERT INTO #companies VALUES('HL Solutions LLC')
INSERT INTO #companies VALUES('Vertisystem Inc.')
INSERT INTO #companies VALUES('SPIN Analytics and Strategy')
INSERT INTO #companies VALUES('MWIDM Inc.')
INSERT INTO #companies VALUES('Cisco Careers')
INSERT INTO #companies VALUES('Digital Management, LLC')
INSERT INTO #companies VALUES('ACI Worldwide')
INSERT INTO #companies VALUES('Booz Allen Hamilton')
INSERT INTO #companies VALUES('Mid-Atlantic Permanente Medical Group PC')
INSERT INTO #companies VALUES('TEKsystems')
INSERT INTO #companies VALUES('Pridevel Consulting, Inc')
INSERT INTO #companies VALUES('Tekvalley, Corp.')
INSERT INTO #companies VALUES('Intralinks')
INSERT INTO #companies VALUES('ENFEC')
INSERT INTO #companies VALUES('Commercial Programming Systems')
INSERT INTO #companies VALUES('Lotus Suites USA')
INSERT INTO #companies VALUES('Cargill, Incorporated')
INSERT INTO #companies VALUES('Baker Hughes a GE Company')
INSERT INTO #companies VALUES('Collabera')
INSERT INTO #companies VALUES('TEKsystems, Inc')
INSERT INTO #companies VALUES('Wimmer Solutions')
INSERT INTO #companies VALUES('The Judge Group')
INSERT INTO #companies VALUES('W.R. Berkley')
INSERT INTO #companies VALUES('T-Mobile')
INSERT INTO #companies VALUES('Tesorio')
INSERT INTO #companies VALUES('Autodesk')
INSERT INTO #companies VALUES('National Renewable Energy Laboratory')
INSERT INTO #companies VALUES('FedEx Services')
INSERT INTO #companies VALUES('Advantine Technologies')
INSERT INTO #companies VALUES('Walmart Stores')
INSERT INTO #companies VALUES('Sysco')
INSERT INTO #companies VALUES('Wayfair LLC')
INSERT INTO #companies VALUES('Libra Services')
INSERT INTO #companies VALUES('Microsoft')
INSERT INTO #companies VALUES('Nigel Frank International US')
INSERT INTO #companies VALUES('QED National')
INSERT INTO #companies VALUES('SOHO Square Solutions')
INSERT INTO #companies VALUES('Net2Source Inc.')
INSERT INTO #companies VALUES('Medline Industries Inc')
INSERT INTO #companies VALUES('Deloitte')
INSERT INTO #companies VALUES('Trupanion')
INSERT INTO #companies VALUES('AppDynamics')
INSERT INTO #companies VALUES('Kane Partners')
INSERT INTO #companies VALUES('The Hershey Company')
INSERT INTO #companies VALUES('California State University')
INSERT INTO #companies VALUES('iHeartMedia, Inc.')
INSERT INTO #companies VALUES('Peterbilt Motors')
INSERT INTO #companies VALUES('SAIC')
INSERT INTO #companies VALUES('Klaxontech')
INSERT INTO #companies VALUES('Resource Consulting Services')
INSERT INTO #companies VALUES('MV Transportation')
INSERT INTO #companies VALUES('Maven Workforce')
INSERT INTO #companies VALUES('Corporate Solutions General, Inc.')
INSERT INTO #companies VALUES('Rhino Recruiting')
INSERT INTO #companies VALUES('CGI Group, Inc.')
INSERT INTO #companies VALUES('Capgemini')
INSERT INTO #companies VALUES('Central California Alliance for Health')
INSERT INTO #companies VALUES('Intuit')
INSERT INTO #companies VALUES('Siemens')
INSERT INTO #companies VALUES('Textio')
INSERT INTO #companies VALUES('DuPont')
INSERT INTO #companies VALUES('HQ Trivia')
INSERT INTO #companies VALUES('Unilever')
INSERT INTO #companies VALUES('ACT')
INSERT INTO #companies VALUES('Kellton Tech')
INSERT INTO #companies VALUES('Peritus Inc.')
INSERT INTO #companies VALUES('Metabyte')
INSERT INTO #companies VALUES('Morning Consult')
INSERT INTO #companies VALUES('WinInfosys, Inc')
INSERT INTO #companies VALUES('Hobsons')
INSERT INTO #companies VALUES('CoSourcing Partners')
INSERT INTO #companies VALUES('Lawrence Harvey')
INSERT INTO #companies VALUES('ServiceLink Information Technology')
INSERT INTO #companies VALUES('ACI Infotech')
INSERT INTO #companies VALUES('TEKPROS Inc')
INSERT INTO #companies VALUES('Dallas/Fort Worth International Airport')
INSERT INTO #companies VALUES('Facebook')
INSERT INTO #companies VALUES('Genesis10')
INSERT INTO #companies VALUES('Pratt & Whitney')
INSERT INTO #companies VALUES('Techgnite LLC')
INSERT INTO #companies VALUES('Aetna')
INSERT INTO #companies VALUES('Windstream')
INSERT INTO #companies VALUES('Scientific Games')
INSERT INTO #companies VALUES('Western Alliance Bank')
INSERT INTO #companies VALUES('Intuit Inc')
INSERT INTO #companies VALUES('Obsidian Security')
INSERT INTO #companies VALUES('Kelaca is an Equal Opportunity Employer')
INSERT INTO #companies VALUES('Mast Global')
INSERT INTO #companies VALUES('Huxley Banking & Financial Services')
INSERT INTO #companies VALUES('ettain group')
INSERT INTO #companies VALUES('Socure')
INSERT INTO #companies VALUES('Gartner')
INSERT INTO #companies VALUES('NIKE INC')
INSERT INTO #companies VALUES('Staples')
INSERT INTO #companies VALUES('New York City DEPT OF INFO TECH & TELECOMM')
INSERT INTO #companies VALUES('WeWork')
INSERT INTO #companies VALUES('Genworth')
INSERT INTO #companies VALUES('Twitter')
INSERT INTO #companies VALUES('ACT, Inc.')
INSERT INTO #companies VALUES('InfiCare Technologies')
INSERT INTO #companies VALUES('Talent Envoy')
INSERT INTO #companies VALUES('Qcentum Technologies')
INSERT INTO #companies VALUES('eProInfosystems LLC')
INSERT INTO #companies VALUES('Last Word Consulting')
INSERT INTO #companies VALUES('DivIHN Integration Inc.')
INSERT INTO #companies VALUES('ApTask')
INSERT INTO #companies VALUES('Omega Hires')
INSERT INTO #companies VALUES('Ameex Technologies Corporation')
INSERT INTO #companies VALUES('VIVA USA INC')
INSERT INTO #companies VALUES('Ascent Services Group')
INSERT INTO #companies VALUES('Tech Mahindra (Americas) Inc.')
INSERT INTO #companies VALUES('Computer Resource Solutions')
INSERT INTO #companies VALUES('Srishti Tek Inc')
INSERT INTO #companies VALUES('Eliassen Group')
INSERT INTO #companies VALUES('CBRE')
INSERT INTO #companies VALUES('BlueVine')
INSERT INTO #companies VALUES('Business and Technology Solutions, LLC')
INSERT INTO #companies VALUES('Roc Search')
INSERT INTO #companies VALUES('CHS Inc.')
INSERT INTO #companies VALUES('Strategic Staffing Solutions')
INSERT INTO #companies VALUES('Glocomms')
INSERT INTO #companies VALUES('PPL Corporation')
INSERT INTO #companies VALUES('Amgen')
INSERT INTO #companies VALUES('Square')
INSERT INTO #companies VALUES('Tech Mahindra')
INSERT INTO #companies VALUES('Computer Futures')
INSERT INTO #companies VALUES('CGI Veterans Jobs')
INSERT INTO #companies VALUES('Lawrence Livermore National Laboratory (LLNL)')
INSERT INTO #companies VALUES('Phaidon International')
INSERT INTO #companies VALUES('Eros Technologies Inc.')
INSERT INTO #companies VALUES('Software Tech Enterprises')
INSERT INTO #companies VALUES('Rishabh Software Pvt. Ltd')
INSERT INTO #companies VALUES('XPO Logistics, Inc.')
INSERT INTO #companies VALUES('Ascendum')
INSERT INTO #companies VALUES('IDC Technologies')
INSERT INTO #companies VALUES('Securus Technologies Inc')
INSERT INTO #companies VALUES('Cygnus Professionals')
INSERT INTO #companies VALUES('Vhire')
INSERT INTO #companies VALUES('Trigint Solutions')
INSERT INTO #companies VALUES('HMS')
INSERT INTO #companies VALUES('NextEra Energy')
INSERT INTO #companies VALUES('Micron')
INSERT INTO #companies VALUES('Aspen Technology')
INSERT INTO #companies VALUES('Children''s Hospital of Philadelphia')
INSERT INTO #companies VALUES('Techstar Consulting Inc.')
INSERT INTO #companies VALUES('Solutions Sync, LLC')
INSERT INTO #companies VALUES('Terminal Contacts LLC')
INSERT INTO #companies VALUES('Techridge, Inc.')
INSERT INTO #companies VALUES('DEEGIT, INC.')
INSERT INTO #companies VALUES('Saicon Consultants Inc.')
INSERT INTO #companies VALUES('Actian')
INSERT INTO #companies VALUES('Austin Fraser')
INSERT INTO #companies VALUES('Wells Fargo')
INSERT INTO #companies VALUES('Allstate')
INSERT INTO #companies VALUES('Leidos')
INSERT INTO #companies VALUES('LyondellBasell')
INSERT INTO #companies VALUES('Prestige Staffing')
INSERT INTO #companies VALUES('Roc Search Inc')
INSERT INTO #companies VALUES('Tephra Inc.')
INSERT INTO #companies VALUES('Gemini Consulting Services')
INSERT INTO #companies VALUES('Synkriom')
INSERT INTO #companies VALUES('Reliable Software Resources')
INSERT INTO #companies VALUES('IT-SCIENT')
INSERT INTO #companies VALUES('Addison Group')
INSERT INTO #companies VALUES('PVR CONSULTING INC')
INSERT INTO #companies VALUES('Tekforce Corporation')
INSERT INTO #companies VALUES('Forsys Inc.')
INSERT INTO #companies VALUES('SpringShine Consulting, Inc.')
INSERT INTO #companies VALUES('RapidIT, Inc')
INSERT INTO #companies VALUES('Hyperion Tech LLC')
INSERT INTO #companies VALUES('Oloop Technology Solutions')
INSERT INTO #companies VALUES('INADEV')
INSERT INTO #companies VALUES('Sparks Group')
INSERT INTO #companies VALUES('Datamatics Consultants, Inc.')
INSERT INTO #companies VALUES('Orabase Solutions LLC.')
INSERT INTO #companies VALUES('Tokio Marine HCC')
INSERT INTO #companies VALUES('RAPID IT INC')
INSERT INTO #companies VALUES('Palmer Group')
INSERT INTO #companies VALUES('Corp2Corp')
INSERT INTO #companies VALUES('Nesco Resource')
INSERT INTO #companies VALUES('Blue Horizon Tek')
INSERT INTO #companies VALUES('Advance Auto Parts')
INSERT INTO #companies VALUES('DIVERSANT, LLC.')
INSERT INTO #companies VALUES('Favor TechConsulting')
INSERT INTO #companies VALUES('Massachusetts General Hospital(MGH)')
INSERT INTO #companies VALUES('Apprio, Inc.')
INSERT INTO #companies VALUES('eSource Technology LLC')
INSERT INTO #companies VALUES('HARMAN International')
INSERT INTO #companies VALUES('Rifiniti')
INSERT INTO #companies VALUES('Visionary Integration Professionals')
INSERT INTO #companies VALUES('Grainger')
INSERT INTO #companies VALUES('Chenega Corporation')
INSERT INTO #companies VALUES('Adobe')
INSERT INTO #companies VALUES('Newt Global')
INSERT INTO #companies VALUES('Varian Medical Systems')
INSERT INTO #companies VALUES('Nestle USA')
INSERT INTO #companies VALUES('Binding Minds, Inc.')
INSERT INTO #companies VALUES('MetroPlus Health Plan')
INSERT INTO #companies VALUES('Next Rev Technologies LLC')
INSERT INTO #companies VALUES('Software Technology, Inc.')
INSERT INTO #companies VALUES('Ajna Infotech')
INSERT INTO #companies VALUES('Walmart eCommerce')
INSERT INTO #companies VALUES('Internet Brands')
INSERT INTO #companies VALUES('Genisys Technologies')
INSERT INTO #companies VALUES('Permanent General Companies, Inc.')
INSERT INTO #companies VALUES('Moody''s Investors Service')
INSERT INTO #companies VALUES('InfoObjects Inc')
INSERT INTO #companies VALUES('Robert Half Technology')
INSERT INTO #companies VALUES('RHP Soft Inc.')
INSERT INTO #companies VALUES('Reed Exhibitions')
INSERT INTO #companies VALUES('SnackNation')
INSERT INTO #companies VALUES('Sira Consulting')
INSERT INTO #companies VALUES('Essential Technologies, Inc')
INSERT INTO #companies VALUES('Scalable Systems')
INSERT INTO #companies VALUES('Soais')
INSERT INTO #companies VALUES('Evonik')
INSERT INTO #companies VALUES('Global Recruiters Network - Seattle')
INSERT INTO #companies VALUES('Engage Partners, Inc.')
INSERT INTO #companies VALUES('Innovizant LLC')
INSERT INTO #companies VALUES('Pfizer')
INSERT INTO #companies VALUES('Irvine Technology Corporation')
INSERT INTO #companies VALUES('Freedom Financial Network')
INSERT INTO #companies VALUES('INNOPLEX')
INSERT INTO #companies VALUES('SunTrust')
INSERT INTO #companies VALUES('Btree Solutions Inc')
INSERT INTO #companies VALUES('UnitedHealth Group')
INSERT INTO #companies VALUES('Capital Markets Placement')
INSERT INTO #companies VALUES('Wood Consulting')
INSERT INTO #companies VALUES('Medidata Solutions')
INSERT INTO #companies VALUES('HARITA INFOTECH')
INSERT INTO #companies VALUES('Renown Health')
INSERT INTO #companies VALUES('Ironnet Cybersecurity Inc')
INSERT INTO #companies VALUES('Freeport-McMoRan Copper & Gold')
INSERT INTO #companies VALUES('comScore, Inc.')
INSERT INTO #companies VALUES('New York Life Insurance Company')
INSERT INTO #companies VALUES('EBSCO Industries Inc')
INSERT INTO #companies VALUES('Westinghouse Electric Company')
INSERT INTO #companies VALUES('Avanade')
INSERT INTO #companies VALUES('Lumber Liquidators')
INSERT INTO #companies VALUES('Children''s Hospital Los Angeles')
INSERT INTO #companies VALUES('Kaygen Inc')
INSERT INTO #companies VALUES('Swinsoft')
INSERT INTO #companies VALUES('Cloudious LLC')
INSERT INTO #companies VALUES('REDLEO SOFTWARE INC.')
INSERT INTO #companies VALUES('Pull Skill Technologies')
INSERT INTO #companies VALUES('Pairwise')
INSERT INTO #companies VALUES('Chipotle')
INSERT INTO #companies VALUES('Kelly IT Resources')
INSERT INTO #companies VALUES('Edward Jones HQ')
INSERT INTO #companies VALUES('Vaco Technology')
INSERT INTO #companies VALUES('Interactive Brokers LLC')
INSERT INTO #companies VALUES('DISYS')
INSERT INTO #companies VALUES('ChaTeck Incorporated')
INSERT INTO #companies VALUES('ZEN3 INFOSOLUTIONS AMERICA INC')
INSERT INTO #companies VALUES('M3BI, LLC.')
INSERT INTO #companies VALUES('APN Consulting Inc')
INSERT INTO #companies VALUES('USAA')
INSERT INTO #companies VALUES('Guidehouse')
INSERT INTO #companies VALUES('Logistics Management Institute')
INSERT INTO #companies VALUES('Nityo Infotech Corporation')
INSERT INTO #companies VALUES('Top Prospect Group')
INSERT INTO #companies VALUES('Ianuly Talent Accelerators')
INSERT INTO #companies VALUES('Enterprise Solutions')
INSERT INTO #companies VALUES('Germane IT Solutions Inc.')
INSERT INTO #companies VALUES('Spar Information Systems')
INSERT INTO #companies VALUES('First Hawaiian Bank')
INSERT INTO #companies VALUES('22nd Century Technologies, Inc.')
INSERT INTO #companies VALUES('MCR, LLC.')
INSERT INTO #companies VALUES('Dentsu Aegis Network')
INSERT INTO #companies VALUES('Techpro Consulting')
INSERT INTO #companies VALUES('Johnson & Johnson Family of Companies')
INSERT INTO #companies VALUES('Anthem, Inc.')
INSERT INTO #companies VALUES('Everest Consulting')
INSERT INTO #companies VALUES('Apidel Technologies')
INSERT INTO #companies VALUES('Soaren Management')
INSERT INTO #companies VALUES('Hydrogen Group')
INSERT INTO #companies VALUES('Technology Consulting, Inc')
INSERT INTO #companies VALUES('Farm Bureau Financial Services')
INSERT INTO #companies VALUES('Myriad Women''s Health')
INSERT INTO #companies VALUES('Kitquant')
INSERT INTO #companies VALUES('NOK-4S')
INSERT INTO #companies VALUES('E-Aspire IT')
INSERT INTO #companies VALUES('Trident Consulting Inc.')
INSERT INTO #companies VALUES('IOMAXIS')
INSERT INTO #companies VALUES('Prosum')
INSERT INTO #companies VALUES('PreCyte Inc')
INSERT INTO #companies VALUES('Inabia Software & Consulting Inc.')
INSERT INTO #companies VALUES('University of Pennsylvania')
INSERT INTO #companies VALUES('NPV Staffing')
INSERT INTO #companies VALUES('Econosoft')
INSERT INTO #companies VALUES('Quadrint, Inc')
INSERT INTO #companies VALUES('Cloudreach')
INSERT INTO #companies VALUES('ASR Analytics, LLC')
INSERT INTO #companies VALUES('The Aerospace Corporation')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Zurich North America Zurich North America 712 reviews Zurich North America (www.zurichna.com) is a leading commercial property-casualty insurance provider serving the global corporate, large ...')
INSERT INTO #companies VALUES('Ubisoft')
INSERT INTO #companies VALUES('US Legislative Branch')
INSERT INTO #companies VALUES('Virginia Premier')
INSERT INTO #companies VALUES('TAE Technologies, Inc.')
INSERT INTO #companies VALUES('Google')
INSERT INTO #companies VALUES('Seattle Children’s')
INSERT INTO #companies VALUES('Jacobs')
INSERT INTO #companies VALUES('ADP')
INSERT INTO #companies VALUES('The Select Group')
INSERT INTO #companies VALUES('General Motors')
INSERT INTO #companies VALUES('Philips')
INSERT INTO #companies VALUES('Caterpillar')
INSERT INTO #companies VALUES('KEYW Corporation')
INSERT INTO #companies VALUES('Acuity, Inc.')
INSERT INTO #companies VALUES('Micron Semiconductor Products, Inc. and Micron Technology, Inc')
INSERT INTO #companies VALUES('Systems Planning and Analysis')
INSERT INTO #companies VALUES('American Heart Association')
INSERT INTO #companies VALUES('Mantech International Corporation')
INSERT INTO #companies VALUES('Karyon Global')
INSERT INTO #companies VALUES('Sigmaways, Inc.')
INSERT INTO #companies VALUES('Predictive Partner LLC')
INSERT INTO #companies VALUES('The World Bank Group')
INSERT INTO #companies VALUES('CH2M & Jacobs')
INSERT INTO #companies VALUES('Pioneer Data Systems Inc')
INSERT INTO #companies VALUES('Chipotle Mexican Grill')
INSERT INTO #companies VALUES('PeaceHealth')
INSERT INTO #companies VALUES('RocketCyber')
INSERT INTO #companies VALUES('Mitre Corporation')
INSERT INTO #companies VALUES('Humana')
INSERT INTO #companies VALUES('Conversion Logic')
INSERT INTO #companies VALUES('Hinge Health')
INSERT INTO #companies VALUES('Data Quantist')
INSERT INTO #companies VALUES('Forescout Technologies Inc.')
INSERT INTO #companies VALUES('Trov')
INSERT INTO #companies VALUES('Equifax')
INSERT INTO #companies VALUES('NOKIA')
INSERT INTO #companies VALUES('Dexcom')
INSERT INTO #companies VALUES('Showtime')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from General Atomics 179 reviews')
INSERT INTO #companies VALUES('Portland General Electric')
INSERT INTO #companies VALUES('Kelly Services')
INSERT INTO #companies VALUES('IDR')
INSERT INTO #companies VALUES('Veear Projects Inc')
INSERT INTO #companies VALUES('Hilton Corporate')
INSERT INTO #companies VALUES('Centene Corporation')
INSERT INTO #companies VALUES('Blue Cross Blue Shield of IL, MT, NM, OK & TX')
INSERT INTO #companies VALUES('Onyx Government Services,LLC')
INSERT INTO #companies VALUES('Ten-X')
INSERT INTO #companies VALUES('Advantage xPO')
INSERT INTO #companies VALUES('GM Financial')
INSERT INTO #companies VALUES('FriendFinder Networks Inc')
INSERT INTO #companies VALUES('Optiver US')
INSERT INTO #companies VALUES('CO-OP Financial Services')
INSERT INTO #companies VALUES('Cambridge Mobile Telematics')
INSERT INTO #companies VALUES('Virgin Pulse')
INSERT INTO #companies VALUES('Mobile Programming LLC')
INSERT INTO #companies VALUES('ISO New England Inc.')
INSERT INTO #companies VALUES('Search Services')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Facebook Facebook 429 reviews Founded in 2004, Facebook’s mission is to give people the power to build community and bring the world closer together. People use Facebo...')
INSERT INTO #companies VALUES('GAF')
INSERT INTO #companies VALUES('Intermedia Advertising')
INSERT INTO #companies VALUES('Conduent')
INSERT INTO #companies VALUES('Teladoc Health, Inc')
INSERT INTO #companies VALUES('Colgate-Palmolive')
INSERT INTO #companies VALUES('O''Reilly Media')
INSERT INTO #companies VALUES('Caliber Home Loans')
INSERT INTO #companies VALUES('Interactive Business Systems (IBS)')
INSERT INTO #companies VALUES('Label Insight')
INSERT INTO #companies VALUES('GEORGIA-PACIFIC')
INSERT INTO #companies VALUES('Redhorse Corporation')
INSERT INTO #companies VALUES('Modis')
INSERT INTO #companies VALUES('Advanced Resources')
INSERT INTO #companies VALUES('Ampcus Inc.')
INSERT INTO #companies VALUES('SoFi')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Siemens Siemens 8,282 reviews Siemens is a global powerhouse focusing on the areas of electrification, automation and digitalization. One of the world’s largest produc...')
INSERT INTO #companies VALUES('ZF')
INSERT INTO #companies VALUES('Accenture')
INSERT INTO #companies VALUES('Bridg')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Lee Health Lee Health 354 reviews Year round warm weather in a peaceful, unspoiled environment...get this AND a rewarding career with Lee Health in Fort Myers, FL. Lee He...')
INSERT INTO #companies VALUES('Conduent, Inc.')
INSERT INTO #companies VALUES('Jobspring Partners')
INSERT INTO #companies VALUES('Tonal')
INSERT INTO #companies VALUES('H2M Group')
INSERT INTO #companies VALUES('CAS Group')
INSERT INTO #companies VALUES('Neustar, Inc.')
INSERT INTO #companies VALUES('ADT Security Services')
INSERT INTO #companies VALUES('Verisk')
INSERT INTO #companies VALUES('Centro')
INSERT INTO #companies VALUES('ADT Corporation')
INSERT INTO #companies VALUES('Job Juncture')
INSERT INTO #companies VALUES('Citi')
INSERT INTO #companies VALUES('Air Liquide')
INSERT INTO #companies VALUES('Ramboll Group')
INSERT INTO #companies VALUES('IHS Markit')
INSERT INTO #companies VALUES('CGI')
INSERT INTO #companies VALUES('Benson Hill Biosystems, Inc')
INSERT INTO #companies VALUES('Vanguard')
INSERT INTO #companies VALUES('KDR Recruitment Ltd')
INSERT INTO #companies VALUES('confidential')
INSERT INTO #companies VALUES('Matrix Resources')
INSERT INTO #companies VALUES('Hallmark')
INSERT INTO #companies VALUES('PeritusHub LLC')
INSERT INTO #companies VALUES('AppleOne')
INSERT INTO #companies VALUES('Strio LLC')
INSERT INTO #companies VALUES('VA Community College Sys')
INSERT INTO #companies VALUES('Schneider Electric')
INSERT INTO #companies VALUES('Zoro')
INSERT INTO #companies VALUES('Software Galaxy Systems, LLC')
INSERT INTO #companies VALUES('Kelly Global Talent Solution')
INSERT INTO #companies VALUES('Information Technology Division')
INSERT INTO #companies VALUES('Viacom')
INSERT INTO #companies VALUES('SpotX')
INSERT INTO #companies VALUES('Ericsson')
INSERT INTO #companies VALUES('The Hartford')
INSERT INTO #companies VALUES('National Security Agency')
INSERT INTO #companies VALUES('3Ci')
INSERT INTO #companies VALUES('Visa')
INSERT INTO #companies VALUES('ENGIE Insight')
INSERT INTO #companies VALUES('Spaceknow Inc.')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Mattel Mattel 650 reviews Barbie is the platinum blonde in power at Mattel, the #1 toy maker in the world. Its products include Barbie and Polly Pocket dolls, Fish...')
INSERT INTO #companies VALUES('Mattel')
INSERT INTO #companies VALUES('ACT Inc.')
INSERT INTO #companies VALUES('Wayfair')
INSERT INTO #companies VALUES('TransUnion')
INSERT INTO #companies VALUES('PACCAR')
INSERT INTO #companies VALUES('Paypal')
INSERT INTO #companies VALUES('SAP')
INSERT INTO #companies VALUES('Southwest Airlines')
INSERT INTO #companies VALUES('Raytheon')
INSERT INTO #companies VALUES('Vitro')
INSERT INTO #companies VALUES('ALTA IT Services LLC')
INSERT INTO #companies VALUES('Princeton Plasma Physics Laboratory')
INSERT INTO #companies VALUES('Insight2Profit')
INSERT INTO #companies VALUES('Equinor US Operations LLC')
INSERT INTO #companies VALUES('Cubic')
INSERT INTO #companies VALUES('Nestle Waters North America')
INSERT INTO #companies VALUES('NVT Staffing')
INSERT INTO #companies VALUES('Starbucks')
INSERT INTO #companies VALUES('Digital First Media')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Cigna Cigna 3,453 reviews At Cigna, we''re more than a health insurance company. We''re a global health service company dedicated to helping people improve their hea...')
INSERT INTO #companies VALUES('JB Hunt')
INSERT INTO #companies VALUES('Pfizer Inc.')
INSERT INTO #companies VALUES('Øptimus Consulting')
INSERT INTO #companies VALUES('Katalyst Healthcares & Life Sciences')
INSERT INTO #companies VALUES('TAE TECHNOLOGIES INC')
INSERT INTO #companies VALUES('Novo Nordisk')
INSERT INTO #companies VALUES('Ascendo Resources')
INSERT INTO #companies VALUES('Advantage Resourcing')
INSERT INTO #companies VALUES('Beacon Health Options')
INSERT INTO #companies VALUES('JEA')
INSERT INTO #companies VALUES('CarMax')
INSERT INTO #companies VALUES('ExecuNet')
INSERT INTO #companies VALUES('KPMG')
INSERT INTO #companies VALUES('Oracle')
INSERT INTO #companies VALUES('Huxley Associates')
INSERT INTO #companies VALUES('AT&T')
INSERT INTO #companies VALUES('MCR Labs')
INSERT INTO #companies VALUES('Sovrn Holdings')
INSERT INTO #companies VALUES('PwC')
INSERT INTO #companies VALUES('Cognizant')
INSERT INTO #companies VALUES('Proofpoint')
INSERT INTO #companies VALUES('State of North Carolina')
INSERT INTO #companies VALUES('Osmo')
INSERT INTO #companies VALUES('Idaho National Laboratory')
INSERT INTO #companies VALUES('Frank Recruitment Group')
INSERT INTO #companies VALUES('Hunter Technical Resources')
INSERT INTO #companies VALUES('Green Key Resources')
INSERT INTO #companies VALUES('Huntington Ingalls Industries (HII-MDIS)')
INSERT INTO #companies VALUES('Verizon')
INSERT INTO #companies VALUES('Ford Motor Company')
INSERT INTO #companies VALUES('Allianz Global Investors')
INSERT INTO #companies VALUES('Reonomy')
INSERT INTO #companies VALUES('Glassbox')
INSERT INTO #companies VALUES('Republic Services')
INSERT INTO #companies VALUES('University of California Berkeley')
INSERT INTO #companies VALUES('Crowe')
INSERT INTO #companies VALUES('Freddie Mac')
INSERT INTO #companies VALUES('MachineZone')
INSERT INTO #companies VALUES('Uber')
INSERT INTO #companies VALUES('Esurance')
INSERT INTO #companies VALUES('CareerBuilder Careers')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Apple Apple 7,040 reviews This is where you can do the best work of your life. Where you’ll join some of the world’s smartest, most innovative people to create ama...')
INSERT INTO #companies VALUES('Radiant Solutions')
INSERT INTO #companies VALUES('Strata Decision Technology, L.L.C.')
INSERT INTO #companies VALUES('Central Pacific Bank')
INSERT INTO #companies VALUES('Tessella Inc.')
INSERT INTO #companies VALUES('EZCORP')
INSERT INTO #companies VALUES('Horizon Health')
INSERT INTO #companies VALUES('Butterfly Network')
INSERT INTO #companies VALUES('TitanData Inc.')
INSERT INTO #companies VALUES('Kavaliro')
INSERT INTO #companies VALUES('CareerBuilder')
INSERT INTO #companies VALUES('Infosoft, Inc.')
INSERT INTO #companies VALUES('Vortexlink')
INSERT INTO #companies VALUES('City of Tacoma')
INSERT INTO #companies VALUES('DOCOMO Innovations, Inc.')
INSERT INTO #companies VALUES('KBR')
INSERT INTO #companies VALUES('TGS')
INSERT INTO #companies VALUES('Pinnacle Partners, Inc')
INSERT INTO #companies VALUES('U.S. Bank')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Walmart Stores Walmart Stores 168,680 reviews Think you know Walmart? Think again. Our top-notch, integrated team is changing the way the world shops and harvesting exciting career-ca...')
INSERT INTO #companies VALUES('Travelers')
INSERT INTO #companies VALUES('Computer Enterprises, Inc. (CEI)')
INSERT INTO #companies VALUES('Pacific Investment Management Company LLC')
INSERT INTO #companies VALUES('Vaco - Dallas')
INSERT INTO #companies VALUES('QUANTRONIX')
INSERT INTO #companies VALUES('American Public Health Association')
INSERT INTO #companies VALUES('Jewelers Mutual Insurance Company')
INSERT INTO #companies VALUES('Packsize, LLC')
INSERT INTO #companies VALUES('Alelo')
INSERT INTO #companies VALUES('Newbold Advisors')
INSERT INTO #companies VALUES('KBRwyle')
INSERT INTO #companies VALUES('ADT')
INSERT INTO #companies VALUES('eXcell')
INSERT INTO #companies VALUES('Genentech')
INSERT INTO #companies VALUES('KOHLS')
INSERT INTO #companies VALUES('Massachusetts General Hospital')
INSERT INTO #companies VALUES('ICONMA')
INSERT INTO #companies VALUES('Amica Insurance')
INSERT INTO #companies VALUES('Primex Process Specialists')
INSERT INTO #companies VALUES('Elder Research Inc')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Grainger Grainger 2,075 reviews Grainger is no stranger to those in need of a wide variety of industrial products. W.W. Grainger distributes more than one million indust...')
INSERT INTO #companies VALUES('DOCOMO Innovations')
INSERT INTO #companies VALUES('Slack')
INSERT INTO #companies VALUES('Quevera')
INSERT INTO #companies VALUES('UiPath')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from KAR Auction Services, Inc. KAR Auction Services, Inc. 411 reviews The KAR group of companies provides everything wholesale-used car sellers and buyers might need, from salvage and used-car auctions t...')
INSERT INTO #companies VALUES('HCA Healthcare')
INSERT INTO #companies VALUES('Benefitfocus')
INSERT INTO #companies VALUES('Sportradar AG')
INSERT INTO #companies VALUES('General Dynamics Information Technology')
INSERT INTO #companies VALUES('Pharmacy Investigators and Consultants')
INSERT INTO #companies VALUES('Essentia Health')
INSERT INTO #companies VALUES('Netflix')
INSERT INTO #companies VALUES('Lumentum Operations LLC')
INSERT INTO #companies VALUES('HCA Corporate')
INSERT INTO #companies VALUES('Plenty')
INSERT INTO #companies VALUES('Care/of')
INSERT INTO #companies VALUES('Big Fish Games')
INSERT INTO #companies VALUES('Toomey Technologies')
INSERT INTO #companies VALUES('Okaya')
INSERT INTO #companies VALUES('Carvana')
INSERT INTO #companies VALUES('Competent Systems, Inc.')
INSERT INTO #companies VALUES('Bloomberg BNA')
INSERT INTO #companies VALUES('ConsultNet')
INSERT INTO #companies VALUES('Discount Tire Company')
INSERT INTO #companies VALUES('TransTech Solution Staffng')
INSERT INTO #companies VALUES('Turnberry Solutions')
INSERT INTO #companies VALUES('Fast Switch, Ltd.')
INSERT INTO #companies VALUES('The Ashlar Group')
INSERT INTO #companies VALUES('Options EPPM LLC')
INSERT INTO #companies VALUES('North Dakota State Government')
INSERT INTO #companies VALUES('UNCOMN, LLC')
INSERT INTO #companies VALUES('Epsilon')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Walmart eCommerce Walmart eCommerce 334 reviews Walmart Global eCommerce is made up of Walmart.com, VUDU, and SamsClub.com and is powered by @Walmartlabs! Our business experts, front...')
INSERT INTO #companies VALUES('The Home Depot')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Steward Health Care Steward Health Care 334 reviews Steward Health Care is committed to providing the highest quality of patient care in the communities where our patients live.')
INSERT INTO #companies VALUES('Sparkfund')
INSERT INTO #companies VALUES('Commvault')
INSERT INTO #companies VALUES('QxBranch')
INSERT INTO #companies VALUES('DriveTime')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Oregon Lottery 4 reviews')
INSERT INTO #companies VALUES('Ulta Beauty')
INSERT INTO #companies VALUES('Best Buy')
INSERT INTO #companies VALUES('ProjectManager.com')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Textio')
INSERT INTO #companies VALUES('Bayer')
INSERT INTO #companies VALUES('Guidewire Software, Inc.')
INSERT INTO #companies VALUES('Symantec')
INSERT INTO #companies VALUES('Bridgestone Americas')
INSERT INTO #companies VALUES('ASAP Solutions')
INSERT INTO #companies VALUES('CORMAC Corporation')
INSERT INTO #companies VALUES('Accolade, Inc.')
INSERT INTO #companies VALUES('Shell')
INSERT INTO #companies VALUES('Movado Group, Inc.')
INSERT INTO #companies VALUES('NOK-Vintun')
INSERT INTO #companies VALUES('American Institutes for Research')
INSERT INTO #companies VALUES('US Department of the Army')
INSERT INTO #companies VALUES('Ally Financial Inc.')
INSERT INTO #companies VALUES('The Standard')
INSERT INTO #companies VALUES('Atrium Health')
INSERT INTO #companies VALUES('Spectrum')
INSERT INTO #companies VALUES('EY')
INSERT INTO #companies VALUES('Zillow Group')
INSERT INTO #companies VALUES('Meet Sally')
INSERT INTO #companies VALUES('Highmark Inc')
INSERT INTO #companies VALUES('Everytown for Gun Safety')
INSERT INTO #companies VALUES('Grubhub')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Taboola 4 reviews')
INSERT INTO #companies VALUES('Complete Intelligence')
INSERT INTO #companies VALUES('091 Cigna Health & Life Ins. Co.')
INSERT INTO #companies VALUES('Publicis Spine')
INSERT INTO #companies VALUES('Network ESC')
INSERT INTO #companies VALUES('McDermott')
INSERT INTO #companies VALUES('Integrated Resources, Inc.')
INSERT INTO #companies VALUES('Discover Financial Services')
INSERT INTO #companies VALUES('Signature Consultants')
INSERT INTO #companies VALUES('King.com')
INSERT INTO #companies VALUES('Deutsche Bank')
INSERT INTO #companies VALUES('L.A. Care Health Plan')
INSERT INTO #companies VALUES('US Tech Solutions, Inc')
INSERT INTO #companies VALUES('UPS')
INSERT INTO #companies VALUES('Under Armour')
INSERT INTO #companies VALUES('o''brien & gere engineers')
INSERT INTO #companies VALUES('Cars.com')
INSERT INTO #companies VALUES('Natural Systems Analysts/USGS')
INSERT INTO #companies VALUES('Astrix Technology Group')
INSERT INTO #companies VALUES('AIC (part of ACS Group)')
INSERT INTO #companies VALUES('The NPD Group')
INSERT INTO #companies VALUES('Techworkers')
INSERT INTO #companies VALUES('Pyramid Consulting, Inc')
INSERT INTO #companies VALUES('Ajulia Executive Search')
INSERT INTO #companies VALUES('General Dynamics Mission Systems')
INSERT INTO #companies VALUES('Computer Recruiters, Inc.')
INSERT INTO #companies VALUES('Trinamix')
INSERT INTO #companies VALUES('Veritude')
INSERT INTO #companies VALUES('LRS')
INSERT INTO #companies VALUES('Interactive Health, INC')
INSERT INTO #companies VALUES('FCA')
INSERT INTO #companies VALUES('Delaware North')
INSERT INTO #companies VALUES('Odyssey Systems Consulting Group')
INSERT INTO #companies VALUES('Jobot')
INSERT INTO #companies VALUES('Mattson Resources')
INSERT INTO #companies VALUES('SCOM')
INSERT INTO #companies VALUES('Parsons')
INSERT INTO #companies VALUES('UCB')
INSERT INTO #companies VALUES('Solutions Resource LLC')
INSERT INTO #companies VALUES('XPO Logistics')
INSERT INTO #companies VALUES('Red Berry Innovations')
INSERT INTO #companies VALUES('Regions Bank')
INSERT INTO #companies VALUES('Ionis Pharmaceuticals')
INSERT INTO #companies VALUES('State of Indiana')
INSERT INTO #companies VALUES('BMO Financial Group')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Eventbrite Eventbrite 6 reviews Eventbrite powers ticketing and registration for more than two million live experiences each year, hosting the world’s largest online sel...')
INSERT INTO #companies VALUES('AKCEA Therapeutics')
INSERT INTO #companies VALUES('Software Technology Inc')
INSERT INTO #companies VALUES('Charlotte''s Web')
INSERT INTO #companies VALUES('Zulily')
INSERT INTO #companies VALUES('CICONIX, LLC')
INSERT INTO #companies VALUES('ERPi')
INSERT INTO #companies VALUES('DBI Staffing')
INSERT INTO #companies VALUES('Pluralsight')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Viola AI')
INSERT INTO #companies VALUES('US Department of the Treasury')
INSERT INTO #companies VALUES('Munich Re America')
INSERT INTO #companies VALUES('Cambia Health')
INSERT INTO #companies VALUES('General Mills Inc.')
INSERT INTO #companies VALUES('Nexus Staffing Solutions, LLC')
INSERT INTO #companies VALUES('Booz Allen Hamilton Inc.')
INSERT INTO #companies VALUES('Rally Health')
INSERT INTO #companies VALUES('Anixter Inc')
INSERT INTO #companies VALUES('Federal Bureau of Investigation')
INSERT INTO #companies VALUES('USA, Bellevue, WA')
INSERT INTO #companies VALUES('Gigster External')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Walmart Stores Walmart Stores 170,627 reviews Think you know Walmart? Think again. Our top-notch, integrated team is changing the way the world shops and harvesting exciting career-ca...')
INSERT INTO #companies VALUES('Spry Squared, Inc.')
INSERT INTO #companies VALUES('Procter and Gamble')
INSERT INTO #companies VALUES('Xavient')
INSERT INTO #companies VALUES('Royal Caribbean Cruises Ltd.')
INSERT INTO #companies VALUES('DICK''S Sporting Goods')
INSERT INTO #companies VALUES('Community College of Rhode Island')
INSERT INTO #companies VALUES('Maven Wave Partners')
INSERT INTO #companies VALUES('TrueCar, Inc.')
INSERT INTO #companies VALUES('DTCC')
INSERT INTO #companies VALUES('V2Soft')
INSERT INTO #companies VALUES('Coherent Germany')
INSERT INTO #companies VALUES('DISH Network')
INSERT INTO #companies VALUES('Coherent, Inc.')
INSERT INTO #companies VALUES('Solvay')
INSERT INTO #companies VALUES('Public Consulting Group, Inc.')
INSERT INTO #companies VALUES('American Cybersystems, Inc. (ACS Group)')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Walmart Stores Walmart Stores 170,761 reviews Think you know Walmart? Think again. Our top-notch, integrated team is changing the way the world shops and harvesting exciting career-ca...')
INSERT INTO #companies VALUES('DataScan')
INSERT INTO #companies VALUES('Tessella')
INSERT INTO #companies VALUES('Confidential Company')
INSERT INTO #companies VALUES('Infovision Consultants Inc')
INSERT INTO #companies VALUES('Shape (ShapeScale)')
INSERT INTO #companies VALUES('Smith & Nephew')
INSERT INTO #companies VALUES('CBTS a Cincinnati Bell Company')
INSERT INTO #companies VALUES('Spectraforce')
INSERT INTO #companies VALUES('Proven Recruiting')
INSERT INTO #companies VALUES('Advantage Solutions')
INSERT INTO #companies VALUES('Dell')
INSERT INTO #companies VALUES('Craft')
INSERT INTO #companies VALUES('WOW! Internet Phone Cable')
INSERT INTO #companies VALUES('Beyondsoft Consulting')
INSERT INTO #companies VALUES('Experian')
INSERT INTO #companies VALUES('CRISIL Limited')
INSERT INTO #companies VALUES('Dollar Shave Club')
INSERT INTO #companies VALUES('ISO')
INSERT INTO #companies VALUES('Brillio')
INSERT INTO #companies VALUES('Worldpay 2018')
INSERT INTO #companies VALUES('LOCKHEED MARTIN CORPORATION')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Microsoft Microsoft 5,611 reviews Microsoft Corporation (NASDAQ: MSFT) is an American public multinational corporation headquartered in Redmond, Washington, USA that devel...')
INSERT INTO #companies VALUES('Scripps Health')
INSERT INTO #companies VALUES('Ridgeback Management Services LLC')
INSERT INTO #companies VALUES('Lincoln Financial')
INSERT INTO #companies VALUES('J.C. Penney Corporation, Inc.')
INSERT INTO #companies VALUES('Procom')
INSERT INTO #companies VALUES('Intuitive Surgical')
INSERT INTO #companies VALUES('Harvard University')
INSERT INTO #companies VALUES('ICW Group')
INSERT INTO #companies VALUES('Akraya Inc.')
INSERT INTO #companies VALUES('GE Corporate')
INSERT INTO #companies VALUES('Shaw Industries')
INSERT INTO #companies VALUES('New York University')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from McAfee 185 reviews')
INSERT INTO #companies VALUES('DCS Corp')
INSERT INTO #companies VALUES('Beacon Hill Staffing Group, LLC')
INSERT INTO #companies VALUES('TripAdvisor')
INSERT INTO #companies VALUES('Entergy')
INSERT INTO #companies VALUES('MetLife')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Neustar, Inc. 6 reviews')
INSERT INTO #companies VALUES('Allstate Corporate Hiring')
INSERT INTO #companies VALUES('Merkle Inc.')
INSERT INTO #companies VALUES('Artech Information Systems LLC')
INSERT INTO #companies VALUES('eHealth')
INSERT INTO #companies VALUES('Chegg')
INSERT INTO #companies VALUES('General Electric')
INSERT INTO #companies VALUES('Slync')
INSERT INTO #companies VALUES('Forcepoint')
INSERT INTO #companies VALUES('The Prosper Group')
INSERT INTO #companies VALUES('Weber Shandwick')
INSERT INTO #companies VALUES('The Computer Merchant, Ltd')
INSERT INTO #companies VALUES('Myriad Technical Services')
INSERT INTO #companies VALUES('Orbital Insight')
INSERT INTO #companies VALUES('PADI Worldwide')
INSERT INTO #companies VALUES('The Kenjya-Trusant Group, LLC')
INSERT INTO #companies VALUES('Real Staffing')
INSERT INTO #companies VALUES('TMX Finance Family of Companies')
INSERT INTO #companies VALUES('Oak Ridge National Laboratory')
INSERT INTO #companies VALUES('Curacao')
INSERT INTO #companies VALUES('JCPenney')
INSERT INTO #companies VALUES('WellCare')
INSERT INTO #companies VALUES('Wish')
INSERT INTO #companies VALUES('SCAN Health Plan')
INSERT INTO #companies VALUES('OpenClassrooms')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Youper')
INSERT INTO #companies VALUES('Cyient')
INSERT INTO #companies VALUES('Nielsen')
INSERT INTO #companies VALUES('Tailored Brands')
INSERT INTO #companies VALUES('C&J Energy Services')
INSERT INTO #companies VALUES('Ring Inc.')
INSERT INTO #companies VALUES('Neotecra, Inc.')
INSERT INTO #companies VALUES('The Creative Group')
INSERT INTO #companies VALUES('Cottonwood Financial')
INSERT INTO #companies VALUES('Intelliswift Software')
INSERT INTO #companies VALUES('Liberty Personnel')
INSERT INTO #companies VALUES('MCR, LLC')
INSERT INTO #companies VALUES('Anadarko Petroleum Corporation')
INSERT INTO #companies VALUES('Daimler')
INSERT INTO #companies VALUES('Stanford University')
INSERT INTO #companies VALUES('Unified Physician Management')
INSERT INTO #companies VALUES('Superior Court of Orange County')
INSERT INTO #companies VALUES('Covance')
INSERT INTO #companies VALUES('Red Alpha')
INSERT INTO #companies VALUES('Mican Technologies')
INSERT INTO #companies VALUES('HTC Global Services, Inc.')
INSERT INTO #companies VALUES('Wayne State University')
INSERT INTO #companies VALUES('Aptiv')
INSERT INTO #companies VALUES('Acclaim Systems')
INSERT INTO #companies VALUES('Ascend Learning')
INSERT INTO #companies VALUES('Randstad Technologies')
INSERT INTO #companies VALUES('Honeywell')
INSERT INTO #companies VALUES('Equian')
INSERT INTO #companies VALUES('Abbott Laboratories')
INSERT INTO #companies VALUES('Auto Club of Southern California')
INSERT INTO #companies VALUES('Waymo')
INSERT INTO #companies VALUES('HII-TSD formerly G2, Inc.')
INSERT INTO #companies VALUES('Ciox Health')
INSERT INTO #companies VALUES('Activision')
INSERT INTO #companies VALUES('Comcentric')
INSERT INTO #companies VALUES('SparkPost')
INSERT INTO #companies VALUES('Federated Investors')
INSERT INTO #companies VALUES('Vortexlink, Inc.')
INSERT INTO #companies VALUES('Compunnel')
INSERT INTO #companies VALUES('Acara Solutions')
INSERT INTO #companies VALUES('Ocean Across Bpm Services pvt ltd')
INSERT INTO #companies VALUES('Highmark Health')
INSERT INTO #companies VALUES('American First Finance, Inc')
INSERT INTO #companies VALUES('Not used')
INSERT INTO #companies VALUES('Red Lambda')
INSERT INTO #companies VALUES('Rakuten Intelligence')
INSERT INTO #companies VALUES('Mars')
INSERT INTO #companies VALUES('PlaceIQ')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from PlaceIQ 10 reviews')
INSERT INTO #companies VALUES('Squarespace')
INSERT INTO #companies VALUES('Milliman')
INSERT INTO #companies VALUES('Riot Games')
INSERT INTO #companies VALUES('Synectics for Management Decisions, Inc')
INSERT INTO #companies VALUES('Abercrombie and Fitch Co.')
INSERT INTO #companies VALUES('K12')
INSERT INTO #companies VALUES('Sabre')
INSERT INTO #companies VALUES('CHUBB')
INSERT INTO #companies VALUES('DAT Solutions, LLC')
INSERT INTO #companies VALUES('Kane Partners LLC')
INSERT INTO #companies VALUES('Genuent')
INSERT INTO #companies VALUES('Ford')
INSERT INTO #companies VALUES('Useready')
INSERT INTO #companies VALUES('Harvey Nash Inc.')
INSERT INTO #companies VALUES('Optimizely')
INSERT INTO #companies VALUES('Digitas')
INSERT INTO #companies VALUES('Averna')
INSERT INTO #companies VALUES('Panasonic Energy of North America')
INSERT INTO #companies VALUES('Synectics Inc.')
INSERT INTO #companies VALUES('Signet Jewelers')
INSERT INTO #companies VALUES('Comcast Corporation')
INSERT INTO #companies VALUES('DAT Solutions')
INSERT INTO #companies VALUES('HireNetworks')
INSERT INTO #companies VALUES('Invenio Search Group, Inc')
INSERT INTO #companies VALUES('Open Systems Technologies')
INSERT INTO #companies VALUES('Booz Allen Hamilton, Inc')
INSERT INTO #companies VALUES('HumCap Recruiting')
INSERT INTO #companies VALUES('Argonne National Lab')
INSERT INTO #companies VALUES('AbilityLab')
INSERT INTO #companies VALUES('Thomas Publishing')
INSERT INTO #companies VALUES('PRA Health Sciences')
INSERT INTO #companies VALUES('Charter Communications')
INSERT INTO #companies VALUES('Systems Planning and Analysis, Inc.')
INSERT INTO #companies VALUES('Amazon.com')
INSERT INTO #companies VALUES('Abbott')
INSERT INTO #companies VALUES('KAR Auction Services Inc')
INSERT INTO #companies VALUES('IBM')
INSERT INTO #companies VALUES('MCR LLC')
INSERT INTO #companies VALUES('Intelligent Switchgear Organization')
INSERT INTO #companies VALUES('Genpact LLC')
INSERT INTO #companies VALUES('Rose International')
INSERT INTO #companies VALUES('Novartis Pharmaceuticals Corporation')
INSERT INTO #companies VALUES('GlaxoSmithKline')
INSERT INTO #companies VALUES('Southern California Edison')
INSERT INTO #companies VALUES('The Endurance International Group Inc')
INSERT INTO #companies VALUES('Career Strategies, Inc.')
INSERT INTO #companies VALUES('Luttrell Staffing Group')
INSERT INTO #companies VALUES('Corporate Careers (TSR)')
INSERT INTO #companies VALUES('The Chubb Corporation')
INSERT INTO #companies VALUES('CDW')
INSERT INTO #companies VALUES('Trianz')
INSERT INTO #companies VALUES('UCS Consulting')
INSERT INTO #companies VALUES('Elicit')
INSERT INTO #companies VALUES('Central Intelligence Agency')
INSERT INTO #companies VALUES('Blackwatch')
INSERT INTO #companies VALUES('Callière Group')
INSERT INTO #companies VALUES('Odyssey Systems Consulting Group, Ltd')
INSERT INTO #companies VALUES('Motorola Solutions')
INSERT INTO #companies VALUES('University of Maryland Baltimore County')
INSERT INTO #companies VALUES('U-Haul')
INSERT INTO #companies VALUES('Zignal Labs')
INSERT INTO #companies VALUES('Gilead Sciences')
INSERT INTO #companies VALUES('Johnson Controls')
INSERT INTO #companies VALUES('Alliance Data card services')
INSERT INTO #companies VALUES('Workbridge Associates')
INSERT INTO #companies VALUES('Ledgent Technology')
INSERT INTO #companies VALUES('Infinity Consulting Solutions')
INSERT INTO #companies VALUES('CHRISTUS Health')
INSERT INTO #companies VALUES('Astellas')
INSERT INTO #companies VALUES('Gardner Resources Consulting, LLC')
INSERT INTO #companies VALUES('KEYENCE')
INSERT INTO #companies VALUES('Pinnacle Partners')
INSERT INTO #companies VALUES('Endevis Professional Contract Staffing')
INSERT INTO #companies VALUES('Bartech Group')
INSERT INTO #companies VALUES('Roblox')
INSERT INTO #companies VALUES('Novartis')
INSERT INTO #companies VALUES('Bell Flight')
INSERT INTO #companies VALUES('Rekruiters')
INSERT INTO #companies VALUES('OGSystems')
INSERT INTO #companies VALUES('Sephora')
INSERT INTO #companies VALUES('InfoVision')
INSERT INTO #companies VALUES('Kraft Analytics Group')
INSERT INTO #companies VALUES('HersheyCareers')
INSERT INTO #companies VALUES('Lifescan')
INSERT INTO #companies VALUES('Wiley')
INSERT INTO #companies VALUES('LexisNexis')
INSERT INTO #companies VALUES('Emailage')
INSERT INTO #companies VALUES('OSI Engineering')
INSERT INTO #companies VALUES('Sysazzle')
INSERT INTO #companies VALUES('AIC')
INSERT INTO #companies VALUES('Flywire')
INSERT INTO #companies VALUES('Full Potential Solutions')
INSERT INTO #companies VALUES('Canon U.S.A., Inc.')
INSERT INTO #companies VALUES('Vail Resorts')
INSERT INTO #companies VALUES('Object Computing Inc.')
INSERT INTO #companies VALUES('MCKEAN DEFENSE/CABRILLO TECHNOLOGIES')
INSERT INTO #companies VALUES('Voluntis')
INSERT INTO #companies VALUES('Hays')
INSERT INTO #companies VALUES('Truckstop.com Careers')
INSERT INTO #companies VALUES('Mastech')
INSERT INTO #companies VALUES('McKinsey & Company')
INSERT INTO #companies VALUES('County of Henrico Department of Information Technology')
INSERT INTO #companies VALUES('GrandCanals')
INSERT INTO #companies VALUES('Radian Group Inc')
INSERT INTO #companies VALUES('Danaher')
INSERT INTO #companies VALUES('PSG Global Solutions')
INSERT INTO #companies VALUES('Videojet')
INSERT INTO #companies VALUES('Lucas Group - Search')
INSERT INTO #companies VALUES('Eli Lilly')
INSERT INTO #companies VALUES('Houston Methodist Hospital')
INSERT INTO #companies VALUES('Solution Partners')
INSERT INTO #companies VALUES('Amyx, Inc')
INSERT INTO #companies VALUES('Engage Partners')
INSERT INTO #companies VALUES('BMO Harris Bank')
INSERT INTO #companies VALUES('Cummins')
INSERT INTO #companies VALUES('InstantServe LLC')
INSERT INTO #companies VALUES('DXC Technology')
INSERT INTO #companies VALUES('TD Bank N.A.')
INSERT INTO #companies VALUES('The Bartech Group Inc')
INSERT INTO #companies VALUES('Mondelez International-Sales')
INSERT INTO #companies VALUES('AtWork Personnel Services – La Palma')
INSERT INTO #companies VALUES('Integrated Resources, Inc')
INSERT INTO #companies VALUES('Intertek')
INSERT INTO #companies VALUES('CALIBRE')
INSERT INTO #companies VALUES('CompTech, Inc.')
INSERT INTO #companies VALUES('Procession Systems')
INSERT INTO #companies VALUES('Parsons Corporation')
INSERT INTO #companies VALUES('US Bank')
INSERT INTO #companies VALUES('Nigel Frank International')
INSERT INTO #companies VALUES('BMW Financial Services, US')
INSERT INTO #companies VALUES('Oxford Solutions')
INSERT INTO #companies VALUES('Dex Media')
INSERT INTO #companies VALUES('MatrixCare')
INSERT INTO #companies VALUES('Harvey Nash, Inc')
INSERT INTO #companies VALUES('NTT DATA Services')
INSERT INTO #companies VALUES('Convergenz, LLC.')
INSERT INTO #companies VALUES('Chicago Transit Authority')
INSERT INTO #companies VALUES('ECS Federal, LLC')
INSERT INTO #companies VALUES('Chico''s FAS, Inc-Shared Services')
INSERT INTO #companies VALUES('In-Depth Genomics')
INSERT INTO #companies VALUES('FedEx Custom Critical')
INSERT INTO #companies VALUES('TreeHouse Foods, Inc.')
INSERT INTO #companies VALUES('Community Care Collaborative')
INSERT INTO #companies VALUES('Paladina Health')
INSERT INTO #companies VALUES('Lawrence Livermore National Security')
INSERT INTO #companies VALUES('Arvato Systems North America, Inc.')
INSERT INTO #companies VALUES('Formation')
INSERT INTO #companies VALUES('Lucky Day')
INSERT INTO #companies VALUES('Proteus Digital Health')
INSERT INTO #companies VALUES('Grid Dynamics')
INSERT INTO #companies VALUES('Kelly Government Solutions')
INSERT INTO #companies VALUES('Insight Global')
INSERT INTO #companies VALUES('Chico''s')
INSERT INTO #companies VALUES('The Jackson Laboratory')
INSERT INTO #companies VALUES('Liberty Mutual Insurance')
INSERT INTO #companies VALUES('CCC Information Services Inc')
INSERT INTO #companies VALUES('ClearBridge Technology Group')
INSERT INTO #companies VALUES('Job Cloud Inc')
INSERT INTO #companies VALUES('Delaware North Companies Inc.')
INSERT INTO #companies VALUES('Veda Professionals')
INSERT INTO #companies VALUES('Fourans LLC')
INSERT INTO #companies VALUES('WW International (formerly Weight Watchers)')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Bixal')
INSERT INTO #companies VALUES('Royce Geospatial')
INSERT INTO #companies VALUES('Imetris Corporation')
INSERT INTO #companies VALUES('High Bridge Consulting')
INSERT INTO #companies VALUES('Duke University and Duke University Health System')
INSERT INTO #companies VALUES('Alaka`ina Foundation Family of Companies')
INSERT INTO #companies VALUES('Frederick National Laboratory')
INSERT INTO #companies VALUES('Matterport')
INSERT INTO #companies VALUES('Carters, Inc')
INSERT INTO #companies VALUES('National General Insurance')
INSERT INTO #companies VALUES('Beeswax')
INSERT INTO #companies VALUES('TTI, Inc.')
INSERT INTO #companies VALUES('Honeywell Intelligrated')
INSERT INTO #companies VALUES('Washington, DC')
INSERT INTO #companies VALUES('Thompson Technologies, Inc')
INSERT INTO #companies VALUES('Quest Diagnostics')
INSERT INTO #companies VALUES('Takeda Pharmaceuticals')
INSERT INTO #companies VALUES('HomeAdvisor')
INSERT INTO #companies VALUES('Capgemini Government Solutions')
INSERT INTO #companies VALUES('Leidos Biomedical Research, Inc.')
INSERT INTO #companies VALUES('Pacific Gas And Electric Company')
INSERT INTO #companies VALUES('Karma Automotive')
INSERT INTO #companies VALUES('DFO Global Performance Commerce Limited')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Taboola 7 reviews')
INSERT INTO #companies VALUES('Quest Diagnostic Health and Wellness')
INSERT INTO #companies VALUES('FRESENIUS')
INSERT INTO #companies VALUES('U.Group')
INSERT INTO #companies VALUES('Polaris Alpha')
INSERT INTO #companies VALUES('BPMLinks')
INSERT INTO #companies VALUES('S&P Global')
INSERT INTO #companies VALUES('Federal Reserve Bank of Cleveland')
INSERT INTO #companies VALUES('T. Rowe Price')
INSERT INTO #companies VALUES('Florida Blue')
INSERT INTO #companies VALUES('neo4j.com')
INSERT INTO #companies VALUES('DiDi Labs')
INSERT INTO #companies VALUES('Vesta Corporation')
INSERT INTO #companies VALUES('NIC Inc.')
INSERT INTO #companies VALUES('COR - 6901 Havana')
INSERT INTO #companies VALUES('Discount Tire Corporate Careers')
INSERT INTO #companies VALUES('Lyra Health')
INSERT INTO #companies VALUES('Kronos Incorporated')
INSERT INTO #companies VALUES('Innovel')
INSERT INTO #companies VALUES('Paladin, Inc')
INSERT INTO #companies VALUES('QuintilesIMS')
INSERT INTO #companies VALUES('Veterans Sourcing Group HQ')
INSERT INTO #companies VALUES('TTEC')
INSERT INTO #companies VALUES('JWT Joveo PPC')
INSERT INTO #companies VALUES('Paladin Consulting, Inc')
INSERT INTO #companies VALUES('Takeda')
INSERT INTO #companies VALUES('Arconic')
INSERT INTO #companies VALUES('Aegon')
INSERT INTO #companies VALUES('AdventHealth')
INSERT INTO #companies VALUES('Metro Systems, Inc.')
INSERT INTO #companies VALUES('CALIBRE Systems, Inc.')
INSERT INTO #companies VALUES('Pioneer Data Systems')
INSERT INTO #companies VALUES('Brown University')
INSERT INTO #companies VALUES('CANA H2R Inc')
INSERT INTO #companies VALUES('Resideo')
INSERT INTO #companies VALUES('Tech Job Microsite')
INSERT INTO #companies VALUES('JMS Technical Solutions')
INSERT INTO #companies VALUES('WELL CARE')
INSERT INTO #companies VALUES('804 Technology')
INSERT INTO #companies VALUES('CLARA analytics, Inc.')
INSERT INTO #companies VALUES('Northern Arizona University')
INSERT INTO #companies VALUES('University of Maryland Medical System')
INSERT INTO #companies VALUES('King County')
INSERT INTO #companies VALUES('Salesforce')
INSERT INTO #companies VALUES('Tential IT')
INSERT INTO #companies VALUES('The Trevor Project')
INSERT INTO #companies VALUES('AdventHealth Information Technology')
INSERT INTO #companies VALUES('Foot Locker, Inc.')
INSERT INTO #companies VALUES('Loyaltylitics')
INSERT INTO #companies VALUES('Finicity')
INSERT INTO #companies VALUES('Love Justice International')
INSERT INTO #companies VALUES('Waste Management')
INSERT INTO #companies VALUES('Kforce Finance and Accounting')
INSERT INTO #companies VALUES('Sunrise Systems, Inc')
INSERT INTO #companies VALUES('Hearst Magazines')
INSERT INTO #companies VALUES('Xcel Energy')
INSERT INTO #companies VALUES('Zion & Zion')
INSERT INTO #companies VALUES('People, Technology & Processes')
INSERT INTO #companies VALUES('University of Washington')
INSERT INTO #companies VALUES('Mattersight')
INSERT INTO #companies VALUES('Kinsa Inc.')
INSERT INTO #companies VALUES('Rev.com')
INSERT INTO #companies VALUES('Nu Skin')
INSERT INTO #companies VALUES('SEMA4')
INSERT INTO #companies VALUES('SSI')
INSERT INTO #companies VALUES('RESILIENT POINT')
INSERT INTO #companies VALUES('BigBear, Inc.')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from KSM Consulting')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Toomey Technologies')
INSERT INTO #companies VALUES('ITL USA')
INSERT INTO #companies VALUES('Civis Analytics')
INSERT INTO #companies VALUES('Dover Corporation')
INSERT INTO #companies VALUES('Zensar Technologies')
INSERT INTO #companies VALUES('VoLo Foundation')
INSERT INTO #companies VALUES('Stellar Peak')
INSERT INTO #companies VALUES('Vans')
INSERT INTO #companies VALUES('VF Corporation')
INSERT INTO #companies VALUES('Ranker')
INSERT INTO #companies VALUES('CoStar Group')
INSERT INTO #companies VALUES('SoftNice Inc')
INSERT INTO #companies VALUES('Hubbell Inc')
INSERT INTO #companies VALUES('BCforward')
INSERT INTO #companies VALUES('ServiceTitan')
INSERT INTO #companies VALUES('MacAulay-Brown, Inc. (MacB)')
INSERT INTO #companies VALUES('ViaSat')
INSERT INTO #companies VALUES('Apogee Integration, LLC')
INSERT INTO #companies VALUES('Credit Sesame')
INSERT INTO #companies VALUES('CultureFit Technology Staffing')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Agile Business Concepts')
INSERT INTO #companies VALUES('The Learning Corp')
INSERT INTO #companies VALUES('Solution Partners Inc.')
INSERT INTO #companies VALUES('VincentBenjamin')
INSERT INTO #companies VALUES('Clarivate')
INSERT INTO #companies VALUES('Convoy')
INSERT INTO #companies VALUES('Okaya Inc')
INSERT INTO #companies VALUES('Scout Clean Energy')
INSERT INTO #companies VALUES('App Annie')
INSERT INTO #companies VALUES('Unlearn.AI')
INSERT INTO #companies VALUES('SolutionIT, Inc.')
INSERT INTO #companies VALUES('Jefferies & Company, Inc.')
INSERT INTO #companies VALUES('Numerator')
INSERT INTO #companies VALUES('University of California San Francisco')
INSERT INTO #companies VALUES('Panasonic Avionics')
INSERT INTO #companies VALUES('Washington State University')
INSERT INTO #companies VALUES('CARTO')
INSERT INTO #companies VALUES('Columbus Technologies and Services, Inc.')
INSERT INTO #companies VALUES('Omnitracs')
INSERT INTO #companies VALUES('Foundation Medicine, Inc.')
INSERT INTO #companies VALUES('MX')
INSERT INTO #companies VALUES('Opendoor')
INSERT INTO #companies VALUES('GE Healthcare')
INSERT INTO #companies VALUES('Path2Response LLC')
INSERT INTO #companies VALUES('Brooksource')
INSERT INTO #companies VALUES('Cummins Inc.')
INSERT INTO #companies VALUES('ROAM ANALYTICS')
INSERT INTO #companies VALUES('Legal & General America')
INSERT INTO #companies VALUES('Walmart')
INSERT INTO #companies VALUES('Silicon Valley Bank')
INSERT INTO #companies VALUES('Nordstrom')
INSERT INTO #companies VALUES('KSM Consulting')
INSERT INTO #companies VALUES('Infostretch Corporation')
INSERT INTO #companies VALUES('Maveneer')
INSERT INTO #companies VALUES('Braxton Healthcare Staffing Agency')
INSERT INTO #companies VALUES('Wolters Kluwer')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Hypergiant')
INSERT INTO #companies VALUES('Oxford Road')
INSERT INTO #companies VALUES('Navy Federal Credit Union')
INSERT INTO #companies VALUES('Dupage Medical Group')
INSERT INTO #companies VALUES('Figure')
INSERT INTO #companies VALUES('Perfect World Entertainment')
INSERT INTO #companies VALUES('Collins Aerospace')
INSERT INTO #companies VALUES('Govini')
INSERT INTO #companies VALUES('Kit Check')
INSERT INTO #companies VALUES('General Mills, Inc')
INSERT INTO #companies VALUES('Skyline AI')
INSERT INTO #companies VALUES('Buchanan Technologies')
INSERT INTO #companies VALUES('Mosaic Data Science')
INSERT INTO #companies VALUES('Nike')
INSERT INTO #companies VALUES('North Highland')
INSERT INTO #companies VALUES('Schaeffler Group')
INSERT INTO #companies VALUES('EmblemHealth')
INSERT INTO #companies VALUES('Marquis Staffing Group')
INSERT INTO #companies VALUES('Cyber Space Technologies LLC')
INSERT INTO #companies VALUES('Infosys Technologies Ltd')
INSERT INTO #companies VALUES('Siri Infosolutions Inc')
INSERT INTO #companies VALUES('CSS, Inc.')
INSERT INTO #companies VALUES('the NBA')
INSERT INTO #companies VALUES('AmerisourceBergen')
INSERT INTO #companies VALUES('Sunshine State Health Plan')
INSERT INTO #companies VALUES('Redjack')
INSERT INTO #companies VALUES('Amazon.com Services, Inc.')
INSERT INTO #companies VALUES('University of Colorado Anschutz Medical Campus')
INSERT INTO #companies VALUES('Well Data Labs')
INSERT INTO #companies VALUES('Daymon')
INSERT INTO #companies VALUES('Hylant')
INSERT INTO #companies VALUES('Warner Bros Careers')
INSERT INTO #companies VALUES('RK Management Consultants, Inc.')
INSERT INTO #companies VALUES('Fossil Group')
INSERT INTO #companies VALUES('PepsiCo')
INSERT INTO #companies VALUES('LogMeIn')
INSERT INTO #companies VALUES('JLL')
INSERT INTO #companies VALUES(' Schneider ')
INSERT INTO #companies VALUES(' IntellaPro ')
INSERT INTO #companies VALUES(' Jefferson Frank ')
INSERT INTO #companies VALUES(' Genesis10 ')
INSERT INTO #companies VALUES(' Quest Diagnostics ')
INSERT INTO #companies VALUES(' TEKsystems, Inc ')
INSERT INTO #companies VALUES(' KellyMitchell ')
INSERT INTO #companies VALUES(' Nigel Frank International US ')
INSERT INTO #companies VALUES(' DISYS ')
INSERT INTO #companies VALUES(' Sterling Medical Corporation ')
INSERT INTO #companies VALUES(' Kelly IT Resources ')
INSERT INTO #companies VALUES(' SCOM ')
INSERT INTO #companies VALUES('Edward Jones')
INSERT INTO #companies VALUES('SITEC')
INSERT INTO #companies VALUES('NEXT Trucking')
INSERT INTO #companies VALUES('Methodist Le Bonheur Healthcare')
INSERT INTO #companies VALUES('Cowen, Inc')
INSERT INTO #companies VALUES(' The Judge Group ')
INSERT INTO #companies VALUES(' Vortexlink ')
INSERT INTO #companies VALUES('Qordoba')
INSERT INTO #companies VALUES('United States Golf Association')
INSERT INTO #companies VALUES('Pacific Northwest National Laboratory')
INSERT INTO #companies VALUES('Company Info Follow Get job updates from Techcyte')
INSERT INTO #companies VALUES('Bay Labs')
INSERT INTO #companies VALUES('GSPANN Technologie')
INSERT INTO #companies VALUES('Grab Taxi')
INSERT INTO #companies VALUES('Bevov')
INSERT INTO #companies VALUES(' Experis ')
INSERT INTO #companies VALUES('PopHealthCare')
INSERT INTO #companies VALUES('TracFone Wireless')
INSERT INTO #companies VALUES('Vision Service Plan')
INSERT INTO #companies VALUES('Amazon Web Services, Inc.')
INSERT INTO #companies VALUES('Tracfone Wireless Inc.')
INSERT INTO #companies VALUES('Applecart')
INSERT INTO #companies VALUES('Staffing the Universe')
INSERT INTO #companies VALUES('UCLA Health')
INSERT INTO #companies VALUES('U.S. Federal Government')
INSERT INTO #companies VALUES('Quicken Loans Inc')
INSERT INTO #companies VALUES('Fabric Genomics')


INSERT INTO employer.ORGANIZATION
select distinct company_name as Organization_Name,
                'https://' + replace(company_name, ' ', '') + '.com' as URL,
                10000 + abs(checksum(newid()) % (select count(*) from platform.LOCATION)) Location_ID
from #companies
where company_name like '[a-zA-Z]%'
and len(company_name) <= 120
;